name: Backend setup and test 🧪
run-name: Backend setup and test
on: [push, pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Pull images
        run: npm run pull-images
      - name: Run tests
        run: npm test

      